name: Pull Request
on:
  workflow_dispatch:
  pull_request:
jobs:
  publish-pr:
    uses: ./.github/workflows/publish-pr.yml
    secrets: inherit
  test-mount:
    needs: publish-pr
    uses: ./.github/workflows/test-mount.yml
    secrets: inherit
    with:
      image-tag: ${{ needs.publish-pr.outputs.digest }}
