name: Pull Request
on:
  workflow_dispatch:
  pull_request:
jobs:
  publish-pr:
    uses: ./.github/workflows/publish-pr.yml
    secrets: inherit

  test-mount:
    needs: publish-pr
    uses: ./.github/workflows/test-mount.yml
    secrets: inherit
    with:
      image-tag: latest@${{ needs.publish-pr.outputs.digest }}
  test-sync:
    needs: publish-pr
    uses: ./.github/workflows/test-sync.yml
    secrets: inherit
    with:
      image-tag: latest@${{ needs.publish-pr.outputs.digest }}
  test-multiple:
    needs: publish-pr
    uses: ./.github/workflows/test-multiple.yml
    secrets: inherit
    with:
      image-tag: latest@${{ needs.publish-pr.outputs.digest }}
  test-namespaced:
    needs: publish-pr
    uses: ./.github/workflows/test-namespaced.yml
    secrets: inherit
    with:
      image-tag: latest@${{ needs.publish-pr.outputs.digest }}
  test-namespaced-neg:
    needs: publish-pr
    uses: ./.github/workflows/test-namespaced-neg.yml
    secrets: inherit
    with:
      image-tag: latest@${{ needs.publish-pr.outputs.digest }}
