on:
  workflow_call:
    inputs:
      image-tag:
        required: false
        type: string
  workflow_dispatch:
jobs:
  mount:
    uses: ./.github/workflows/test-e2e.yml
    secrets: inherit
    with:
      image-tag: ${{ inputs.image-tag }}
      type: mount
